globals:
    afterEach: false
    beforeEach: false
    describe: false
    expect: false
    it: false
    jasmine: false
    pending: false
    spyOn: false
    waits: false
    waitsFor: false
    xdescribe: false
    xit: false

    beforeAll: false
    afterAll: false
    runs: false